### ISSUE TITLE
Fails on Mobile "not a function"

### ISSUE THREAD

**Issue by brimwats** [samwho/obsidian-wikidata-importer#2]
I get the below issue when I use the importer on Android for wdID: Q33057

.. for some reason the image won't attach, but the error reads "Error fetching properties for entity Q33057:
TypeError: response.json is not a function"

**Comment by samwho** [comment]
I suspect this might be that the request to Wikipedia failed. I didn't set up great error handling. Do you get this error consistently? 🙂

**Comment by brimwats** [comment]
let me try some more examples tomorrow!

**Comment by visualrobots** [comment]
`"Error fetching properties for entity Q33057: TypeError: response.json is not a function"`

Same here. Happens with all requests (e.g. Q2, Q42, Q33057, ...).

**Comment by samwho** [comment]
Thanks for the PR on this @jhjaggars. I've made a release, can you check that fixes the problem? New release is 1.0.5 because there was already a 1.0.4 tag in the repo 🙈

**Comment by jhjaggars** [comment]
Yep it’s working for me.

**Comment by samwho** [comment]
I'm going to close this. Please reopen if you're still experiencing the problem!
