### ISSUE TITLE
[Feature Request] settings to exclude/include properties

### ISSUE THREAD

**Issue by cleonibbles** [samwho/obsidian-wikidata-importer#7]
For example, when I'm importing a movie I don't necessarily want the facebook name or award nominations (and they clutter the properties), but I also would like to import the imdb id without importing every other id.

This is possibly one of the most useful plugins in my vault, so thank you for developing it!

**Comment by samwho** [comment]
Thank you for the kind words! I can't promise when I'll get around to this, but I agree it's a good feature request.
